# Generated by Django 3.2.7 on 2021-10-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=32)),
                ('AccountNumber', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MethodToPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('typeName', models.CharField(max_length=64)),
                ('categories', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reciver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryWay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentWay', to='product.card')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AddCart', to='product.methodtopay')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='product.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ammount', models.FloatField()),
                ('PaymentWay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentMethod', to='product.card')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentAccount', to='product.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.CharField(max_length=64)),
                ('CheckOut', models.IntegerField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='product.reciver')),
                ('ProductName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Plant', to='product.products')),
            ],
        ),
    ]
